version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8888:8888"
    volumes:
       - /var/lib/jenkins/workspace/testing/app/backend:/app


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
