version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=8888
      - DATABASE=mongodb://mongodb:27017/yourdbname
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_FILE_BASE_URL=http://localhost:8888/
      - VITE_BACKEND_SERVER=http://localhost:8888/
      - PROD=true
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local