apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: backend
        image: mern-backend
        ports:
        - containerPort: 8888
        env:
        - name: DATABASE
          value: "mongodb://mongo-service:27017/mernapp"
        - name: JWT_SECRET
          value: "some_jwt_secret"
      - name: frontend
        image: mern-frontend
        ports:
        - containerPort: 3000
