apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
  - name: frontend
    port: 3000
    targetPort: 3000
  - name: backend
    port: 8888
    targetPort: 8888
